# Generated by Django 5.0.7 on 2024-08-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_remove_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quantity',
        ),
    ]
