# Generated by Django 5.0.7 on 2024-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
