# Generated by Django 4.2.15 on 2024-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0007_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
